# Generated by Django 2.1.5 on 2019-10-23 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cursoTecnico', '0003_teste'),
    ]

    operations = [
        migrations.DeleteModel(
            name='teste',
        ),
    ]
